@startuml

hide footbox
title Admission : studentConfirm
actor Student
participant Platform
entity AuthenticationService
entity AdmissionService
database Repository

Student -> Platform : POST(student)
activate Platform

ref over Student, Platform, AuthenticationService: authentication_verifyStudent

alt try

    Platform -> Repository: findYearEnrollmentBy(Student student, int year)
    Repository -> Platform : return YearEnrollment candidate

    Platform -> AdmissionService : confirmCandidate(YearEnrollment candidate)
    activate AdmissionService
    AdmissionService -> Platform : return true
    deactivate AdmissionService

    Platform -> Student : HTTP/200
    
else catch CandidateOutOfDeadlineException e
    
    Platform -> Student: HTTP/<code>, msg: e
    deactivate Platform
end
@enduml