@startuml

hide footbox
title Admission : selectUniversity
actor Student
participant Platform
entity AuthenticationService
entity AdmissionService

Student -> Platform : DELETE(student, enrollment)
activate Platform

ref over Student, Platform, AuthenticationService: authentication_verifyStudent


alt try

    Platform -> AdmissionService: remove(Enrollment wish)
    activate AdmissionService
    AdmissionService -> Platform: return Enrollment deleted_wish
    deactivate AdmissionService

    Platform -> Student : HTTP/200, msg: deleted_wish

else catch EnrollmentDeletionException e

    Platform -> Student : HTTP/404, msg: e

else catch CandidateViolationException e

    Platform -> Student : HTTP/500, msg: e
    deactivate Platform
end


@enduml